server:
  port: 8082

spring:
  application:
    name: fraud
  banner:
    location: banner.txt
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true